services:
  app:
    build:
      context: .
      dockerfile: docker/stg/php/Dockerfile
    container_name: debate_match_app
    restart: unless-stopped
    command: php-fpm
    environment:
      - "APP_NAME=${APP_NAME}"
      - "APP_ENV=staging"
      - "APP_URL=https://stg.debate-match.com"
      - "APP_KEY=${APP_KEY}"
      - "APP_LOCALE=${APP_LOCALE}"
      - "APP_FALLBACK_LOCALE=${APP_FALLBACK_LOCALE}"
      - "APP_FAKER_LOCALE=${APP_FAKER_LOCALE}"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_CLIENT=${REDIS_CLIENT}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "PUSHER_APP_ID=${PUSHER_APP_ID}"
      - "PUSHER_APP_KEY=${PUSHER_APP_KEY}"
      - "PUSHER_APP_SECRET=${PUSHER_APP_SECRET}"
      - "PUSHER_HOST=${PUSHER_HOST}"
      - "PUSHER_PORT=${PUSHER_PORT}"
      - "PUSHER_SCHEME=${PUSHER_SCHEME}"
      - "PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}"
      - "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
      - "OPENROUTER_CHAT_MODEL=${OPENROUTER_CHAT_MODEL}"
      - "OPENROUTER_EVALUATION_MODEL=${OPENROUTER_EVALUATION_MODEL}"
      - "SESSION_DRIVER=${SESSION_DRIVER:-file}"
      - "CACHE_DRIVER=${CACHE_DRIVER:-file}"
      - "QUEUE_CONNECTION=${QUEUE_CONNECTION:-redis}"
      - "SENTRY_LARAVEL_DSN=${SENTRY_LARAVEL_DSN}"
      - "SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-1.0}"
      - "AWS_SNS_NOTIFICATION_TOPIC_ARN=${AWS_SNS_NOTIFICATION_TOPIC_ARN}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_REGION=${AWS_REGION}"
      - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
      - "SQS_QUEUE=${SQS_QUEUE}"
      - "SQS_PREFIX=${SQS_PREFIX}"
      - "SQS_SUFFIX=${SQS_SUFFIX}"
      - "AI_USER_ID=${AI_USER_ID}"
      - "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}"
      - "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}"
      - "GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}"
      - "SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}"
      - "NODE_ENV=${NODE_ENV}"
    volumes:
      - ./.env:/var/www/html/.env
      - public-data:/var/www/html/public
    networks:
      - sail
    depends_on:
      - redis

  nginx:
    image: nginx:1.25-alpine
    container_name: debate_match_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/stg/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/ec2-user/app/data/certbot/www:/var/www/certbot
      - public-data:/var/www/html/public:ro

    networks:
      - sail
    depends_on:
      - app

  worker:
    build:
      context: .
      dockerfile: docker/stg/php/Dockerfile
    container_name: debate_match_worker
    restart: unless-stopped
    environment:
      - "APP_ENV=staging"
      - "DB_CONNECTION=mysql"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_CLIENT=${REDIS_CLIENT}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "PUSHER_APP_ID=${PUSHER_APP_ID}"
      - "QUEUE_CONNECTION=redis"
      - "PUSHER_APP_KEY=${PUSHER_APP_KEY}"
      - "PUSHER_APP_SECRET=${PUSHER_APP_SECRET}"
      - "PUSHER_HOST=${PUSHER_HOST}"
      - "PUSHER_PORT=${PUSHER_PORT}"
      - "PUSHER_SCHEME=${PUSHER_SCHEME}"
      - "PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}"
      - "OPENROUTER_API_KEY=${OPENROUTER_API_KEY}"
      - "OPENROUTER_CHAT_MODEL=${OPENROUTER_CHAT_MODEL}"
      - "OPENROUTER_EVALUATION_MODEL=${OPENROUTER_EVALUATION_MODEL}"
      - "SESSION_DRIVER=${SESSION_DRIVER:-file}"
      - "CACHE_DRIVER=${CACHE_DRIVER:-file}"
      - "SENTRY_LARAVEL_DSN=${SENTRY_LARAVEL_DSN}"
      - "SENTRY_TRACES_SAMPLE_RATE=${SENTRY_TRACES_SAMPLE_RATE:-1.0}"
      - "AWS_SNS_NOTIFICATION_TOPIC_ARN=${AWS_SNS_NOTIFICATION_TOPIC_ARN}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_REGION=${AWS_REGION}"
      - "AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}"
      - "SQS_QUEUE=${SQS_QUEUE}"
      - "SQS_PREFIX=${SQS_PREFIX}"
      - "SQS_SUFFIX=${SQS_SUFFIX}"
      - "AI_USER_ID=${AI_USER_ID}"
    volumes:
      - ./.env:/var/www/html/.env
    networks:
      - sail
    depends_on:
      - app
      - redis

  redis:
    image: redis:7-alpine
    container_name: debate_match_redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
      - ./docker/stg/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  sail:
    driver: bridge

volumes:
  redis-data:
    driver: local
  public-data:
    driver: local
