<?php

return [
    'formats' => [
        // NPDA Parliamentary Debate Format Key
        'format_name_npda_parliamentary' => [
            1 => ['speaker' => '', 'name' => 'suggestion_prep_time', 'duration' => 20 * 60, 'is_prep_time' => true, 'is_questions' => false],
            2 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_constructive', 'duration' => 7 * 60, 'is_prep_time' => false, 'is_questions' => true],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_1st_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => true],
            4 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => true],
            5 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => true],
            6 => ['speaker' => 'negative', 'name' => 'suggestion_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            7 => ['speaker' => 'affirmative', 'name' => 'suggestion_rebuttal', 'duration' => 5 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
        // NSDA Policy Debate Format Key
        'format_name_nsda_policy' => [
            1 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => false],
            2 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_1st_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => false],
            4 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            5 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => false],
            6 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            7 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_constructive', 'duration' => 8 * 60, 'is_prep_time' => false, 'is_questions' => false],
            8 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            9 => ['speaker' => 'negative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 5 * 60, 'is_prep_time' => false, 'is_questions' => false],
            10 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 5 * 60, 'is_prep_time' => false, 'is_questions' => false],
            11 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 5 * 60, 'is_prep_time' => false, 'is_questions' => false],
            12 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 5 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
        // NSDA Lincoln-Douglas Debate Format Key
        'format_name_nsda_ld' => [
            1 => ['speaker' => 'affirmative', 'name' => 'suggestion_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            2 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_constructive', 'duration' => 7 * 60, 'is_prep_time' => false, 'is_questions' => false],
            4 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            5 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            6 => ['speaker' => 'negative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            7 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
            8 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
        // NADA High School Format Key
        'format_name_nada_high' => [
            1 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            2 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 1 * 60, 'is_prep_time' => true, 'is_questions' => false],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            4 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 1 * 60, 'is_prep_time' => true, 'is_questions' => false],
            5 => ['speaker' => 'negative', 'name' => 'suggestion_1st_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            6 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 1 * 60, 'is_prep_time' => true, 'is_questions' => false],
            7 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            8 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 1 * 60, 'is_prep_time' => true, 'is_questions' => false],
            9 => ['speaker' => 'negative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            10 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            11 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            12 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            13 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            14 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            15 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
        // HEnDA Format Key
        'format_name_henda' => [
            1 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_constructive', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            2 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 1 * 60, 'is_prep_time' => true, 'is_questions' => false],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 2 * 60, 'is_prep_time' => false, 'is_questions' => true],
            4 => ['speaker' => 'negative', 'name' => 'suggestion_constructive', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            5 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 1 * 60, 'is_prep_time' => true, 'is_questions' => false],
            6 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 2 * 60, 'is_prep_time' => false, 'is_questions' => true],
            7 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            8 => ['speaker' => 'negative', 'name' => 'suggestion_attack', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
            9 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 2 * 60, 'is_prep_time' => false, 'is_questions' => true],
            10 => ['speaker' => 'affirmative', 'name' => 'suggestion_attack', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
            11 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 2 * 60, 'is_prep_time' => false, 'is_questions' => true],
            12 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            13 => ['speaker' => 'affirmative', 'name' => 'suggestion_defense', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
            14 => ['speaker' => 'negative', 'name' => 'suggestion_defense', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
            15 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            16 => ['speaker' => 'affirmative', 'name' => 'suggestion_summary', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
            17 => ['speaker' => 'negative', 'name' => 'suggestion_summary', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
        // CoDA Format Key
        'format_name_coda' => [
            1 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            2 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            4 => ['speaker' => 'negative', 'name' => 'suggestion_1st_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            5 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            6 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            7 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            8 => ['speaker' => 'negative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            9 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            10 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            11 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 3 * 60, 'is_prep_time' => true, 'is_questions' => false],
            12 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            13 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 3 * 60, 'is_prep_time' => true, 'is_questions' => false],
            14 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
        // JDA Format Key
        'format_name_jda' => [
            1 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            2 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            3 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            4 => ['speaker' => 'negative', 'name' => 'suggestion_1st_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            5 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            6 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            7 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            8 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            9 => ['speaker' => 'negative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            10 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_constructive', 'duration' => 6 * 60, 'is_prep_time' => false, 'is_questions' => false],
            11 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            12 => ['speaker' => 'affirmative', 'name' => 'suggestion_questioning', 'duration' => 3 * 60, 'is_prep_time' => false, 'is_questions' => true],
            13 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            14 => ['speaker' => 'negative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            15 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            16 => ['speaker' => 'affirmative', 'name' => 'suggestion_1st_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            17 => ['speaker' => 'negative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            18 => ['speaker' => 'negative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
            19 => ['speaker' => 'affirmative', 'name' => 'suggestion_prep_time', 'duration' => 2 * 60, 'is_prep_time' => true, 'is_questions' => false],
            20 => ['speaker' => 'affirmative', 'name' => 'suggestion_2nd_rebuttal', 'duration' => 4 * 60, 'is_prep_time' => false, 'is_questions' => false],
        ],
    ],
];
